[package]
name = "RepeatMacro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "repeat_macro"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.76"
quote = "*"
syn = "2.0.48"
